### ISSUE TITLE
Add fields via application.properties

### ISSUE THREAD

**Issue by panchitoboy** [quarkiverse/quarkiverse-logging-json#18]
First, i really want to thanks you for the effort to have structured logging in quarkus.

I have a question (and a possible request). Is there a way to set some constants in the log via application.properties?

something like: quarkis.logging.json."serviceName".value=test

Log: 

{ serviceName: "test" , message:"message"}

Regards

**Comment by SlyngDK** [comment]
It's not possible right now, only foreach message using `StructuredArgument`.

I will implement it, after the feature I am currently working on.

**Comment by SlyngDK** [comment]
I have just release version 0.1.5, with this feature.

**Comment by panchitoboy** [comment]
Thanks :)
