### ISSUE TITLE
How do we add the extension to a project?

### ISSUE THREAD

**Issue by javadevmtl** [quarkiverse/quarkiverse-logging-json#37]
Hi using the latest Quarkus 1.9CR1

 I tried to run...

`./gradlew addExtension --extensions="quarkiverse-logging-json"`

But it's not adding the extension.

I guess we just add the extension manually?

**Comment by SlyngDK** [comment]
This is a common question in the use of extensions from quarkiverse.
I have asked the question in zulip, and will get back.

I know there is ongoing work, on getting quarkiverse, integrated with the rest of quarkus ecosystem. I think this is part of that.

Yes, right now it is adding a dependency manual.

**Comment by SlyngDK** [comment]
Answer is here https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkiverse.20-.20Ecosystem.20CI/near/214102085

Working in progress...
