### ISSUE TITLE
How do we change the field names?

### ISSUE THREAD

**Issue by javadevmtl** [quarkiverse/quarkiverse-logging-json#38]
I tried the below combinations...

`quarkus.log.console.json.timestamp.fieldName=foo`
`quarkus.log.console.json.timestamp.field-name=foo`

But neither worked

If you tell me, I'm willing to help you document it on the README unless you want to do it?

**Comment by SlyngDK** [comment]
You are missing the `fields` part.
`quarkus.log.console.json.fields.timestamp.field-name=foo`

The publishing of the docs are WIP, in the quarkiverse ecosystem.

**Comment by gsmet** [comment]
@SlyngDK btw, I was wondering if we should leverage CDI to be able to entirely replace the serialization machinery and be able to  produce entirely customized JSON.

I'm not sure it's part of the scope of this extension though :).

**Comment by SlyngDK** [comment]
@gsmet I'm not quite sure what you mean?
Are you talking about quarkus providing something like `io.quarkiverse.loggingjson.JsonGenerator`?
I am not seeing that as a part to discuss on this issue, this is handling only about configuration.

**Comment by aidenmdcurtis** [comment]
@SlyngDK Is this functionality broken? I have tried to change the field name of timestamp as indicated, and it does not work. My full configuration is here:
```quarkus.log.level=INFO
quarkus.log.console.json.pretty-print=true
quarkus.log.console.json.date-format=dd/MM/yyyy HH:mm:ss
quarkus.log.console.json.fields.timestamp.field-name=foo
```

All of the other configuration options work fine.
