### ISSUE TITLE
Quarkiverse is ignoring zone-id

### ISSUE THREAD

**Issue by javadevmtl** [quarkiverse/quarkiverse-logging-json#39]
Hi I tried the default quarkus json logger with: `quarkus.log.console.json.zone-id=UTC` and it works. When I enable quarkiverse it seems that the zone-id is ignore.

Looking at the configs: `https://github.com/quarkiverse/quarkiverse-logging-json/blob/master/runtime/src/main/java/io/quarkiverse/loggingjson/Config.java` 

It seems missing or is it supposed to inherit it?

**Comment by SlyngDK** [comment]
That is not implemented yet, I will add it to the list of requested features.

**Comment by SlyngDK** [comment]
@javadevmtl I have just released `0.1.7`, with support for zone id.

Config to use for UTC:
```quarkus.log.console.json.fields.timestamp.zone-id="UTC"```
