### ISSUE TITLE
default Quarkus JSON logging and quarkiverse-logging-json

### ISSUE THREAD

**Issue by wwn** [quarkiverse/quarkiverse-logging-json#57]
Hello guys
With both dependencies: io.quarkus:quarkus-logging-json and io.quarkiverse.loggingjson:quarkiverse-logging-json it complains about 

> "Multiple matching properties for name "log.console.json" property was matched by both boolean io.quarkus.logging.json.runtime.JsonConfig.enable and boolean io.quarkiverse.loggingjson.Config.enable. This is likely because you have an incompatible combination of extensions that both define the same properties (e.g. including both reactive and blocking database extensions)"

I need quarkiverse-logging-json for additional fields and Structured arguments. How can I use it in parallel to default Quarkus JSON logging?

**Comment by SlyngDK** [comment]
`quarkiverse-logging-json` is alternative to `quarkus-logging-json`, it will not sense to using both.
Both is logging the same messages, `quarkiverse-logging-json` is a more customizable implementation.

If you need the structured arguments, just remove `io.quarkus:quarkus-logging-json` from dependencies.
If you are missing a feature, that will make sense in this project then create and issue for that.

**Comment by wwn** [comment]
thx!
