### ISSUE TITLE
Improvement of custom JsonLoggingProvider docs

### ISSUE THREAD

**Issue by ferencbeutel4711** [quarkiverse/quarkiverse-logging-json#59]
Hello there,

we needed a lot of time unfortunately to figure out why our custom json provider was not used and found out eventually, that it was removed because of a quarkus optimization:

https://quarkus.io/blog/quarkus-dependency-injection/#removing-unused-beans

maybe it would be helpful to document the need to annotate the custom json provider with @Unremovable in the code example or link the feature and write a sentence or two for documentation purposes :)

**Comment by SlyngDK** [comment]
Thx for feedback, the docs part for quarkiverse, just got available to start use, so that is a task for me to start looking at.

The removal of unsed beans, sounds like a bug in this library.
It will be great help with a reproducer of the issue.

**Comment by SlyngDK** [comment]
I was able to reproduce the error about removing unused beans, and fixed the issue in release 0.2.1.
Can you confirm that 0.2.1 fixes your issue, and you are not required to use the `@Unremovable` anymore?

I have created #63 for the work on documentation.
